version: "3.9"

services:
  workspace:
    build:
      context: .
      dockerfile: ./docker/workspace/Dockerfile
    container_name: go-ecs-batch-sample-workspace
    tty: true
    volumes:
      - .:/go/src/github.com/mkaiho/go-ecs-batch-sample
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /go/src/github.com/mkaiho/go-ecs-batch-sample
    ports:
      - 3000:3000
